# -*- coding: utf-8 -*-
"""domain_classification(1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XEjKB72nhFgX51VtMxVSyRE_otyGbtEG
"""

import torch
import json
from transformers import AutoModelForSequenceClassification, AutoTokenizer
from utils import get_device

device = get_device()

model = AutoModelForSequenceClassification.from_pretrained("cardiffnlp/tweet-topic-21-multi")
tokenizer = AutoTokenizer.from_pretrained("cardiffnlp/tweet-topic-21-multi")
label_map = {
    7: 'fitness_&_health',
    8: 'food_&_dining',
    12: 'news_&_social_concern',
    15: 'science_&_technology'
}


def generate_domain(doc_title, doc_content):
    """
    Returns the domain class given
    """
    # model = model.to(device)
    inputs = tokenizer(f'{doc_title} {doc_content}', return_tensors='pt', max_length=128, truncation=True)
    # inputs = inputs.to(device)
    outputs = model(**inputs)
    logits = outputs.logits.to('cpu')
    pred = label_map.get(int(torch.argmax(logits)), 'other')  # scale classes down to 5 only
    return pred